name: Tests

on:
  push:
    branches:
      - master
  pull_request:

permissions: {}

jobs:
  detect-modules:
    runs-on: ubuntu-latest
    container:
      image: lahmanja/devcontainer@sha256:a953bf44772cf97b1cff9ab6d47897aa3cba6cecf6a18194793cbfe0066b9681
      options: --user root
    outputs:
      modules: ${{ steps.set-modules.outputs.modules }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - id: set-modules
        run: echo "modules=$(go list -m -json | jq -s '.' | jq -c '[.[].Dir]')" >> "$GITHUB_OUTPUT"

  golang:
    needs: detect-modules
    runs-on: ubuntu-latest
    container:
      image: lahmanja/devcontainer@sha256:a953bf44772cf97b1cff9ab6d47897aa3cba6cecf6a18194793cbfe0066b9681
      options: --user root
    strategy:
      matrix:
        modules: ${{ fromJSON(needs.detect-modules.outputs.modules) }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
          fetch-depth: 0
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - run: apt-get update && apt-get install -y --no-install-recommends libasound2-dev
      - run: go mod tidy
        working-directory: ${{ matrix.modules }}
      - run: git diff --exit-code go.mod go.sum
        working-directory: ${{ matrix.modules }}
      - run: go test ./...
        working-directory: ${{ matrix.modules }}
        continue-on-error: true
      - name: golangci-lint ${{ matrix.modules }}
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          working-directory: ${{ matrix.modules }}
        continue-on-error: true

  pre-commit:
    runs-on: ubuntu-latest
    container:
      image: lahmanja/devcontainer@sha256:a953bf44772cf97b1cff9ab6d47897aa3cba6cecf6a18194793cbfe0066b9681
      options: --user root
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
          fetch-depth: 0
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: prek
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            prek run --from-ref "${{ github.event.pull_request.base.sha }}" --to-ref "${{ github.event.pull_request.head.sha }}"
          else
            prek run --all-files
          fi
